/**
 * All user-facing strings, in Albanian.
 *
 * Kept in one place so copy can be reviewed and corrected without touching
 * components — the pilot's users are Albanian-speaking, and the wording still
 * needs a native-speaker pass.
 */
export const labels = {
  app: {
    name: "SiteTrack",
  },
  nav: {
    technician: "Tekniku",
    engineer: "Inxhinieri",
  },
  technician: {
    title: "Ditari i sotëm",
    tabs: {
      materials: "Materiale",
      labor: "Fuqi punëtore",
    },
    addMaterial: "Shto material",
    addLabor: "Shto punëtor",
    subtotalMaterials: "Materiale",
    subtotalLabor: "Fuqi punëtore",
    dayTotal: "Kosto e ditës",
    submit: "Paraqit ditën",
    submitting: "Duke paraqitur…",
    submitHint: "Do t’i dërgohet inxhinierit për miratim",
    emptyMaterials: "Asnjë material i regjistruar sot",
    emptyLabor: "Asnjë punëtor i regjistruar sot",
    otherTabHint: "kalo te skeda tjetër për t’i parë",
    noProject: "Nuk je caktuar ende në asnjë projekt. Pyet inxhinierin tënd.",
    chooseMaterial: "Zgjidh material",
    chooseLabor: "Zgjidh rolin",
    quantity: "Sasia",
    workers: "Punëtorë",
    hours: "Orë",
    lineCost: "Kosto e rreshtit",
    addToLog: "Shto në ditar",
    cancel: "Anulo",
    remove: "Hiq",
    status: {
      draft: "Draft",
      submitted: "Paraqitur",
      approved: "Miratuar",
      rejected: "Refuzuar",
    },
  },
  engineer: {
    title: "Paneli i inxhinierit",
    navDashboard: "Paneli",
    navTeam: "Ekipi",
  },
  team: {
    title: "Ekipi",
    addTechnician: "Shto teknik",
    addEngineer: "Shto inxhinier",
    plural: { technician: "teknikë", engineer: "inxhinierë" },
    columns: { name: "Emri", email: "Email", status: "Statusi" },
    status: { active: "Aktiv", invited: "Në pritje", deactivated: "Çaktivizuar" },
    invitedAgo: "U ftua",
    resend: "Dërgo sërish",
    deactivate: "Çaktivizo",
    reactivate: "Aktivizo",
    empty: "Askush ende. Shto personin e parë.",
    panelHint: "Do të marrë një email me një link për të hyrë. Pa fjalëkalim.",
    firstName: "Emri",
    lastName: "Mbiemri",
    email: "Email",
    project: "Projekti",
    role: "Roli",
    send: "Dërgo ftesën",
    sending: "Duke dërguar…",
    linkHint: "Linku vlen 24 orë.",
    close: "Mbyll",
    cancel: "Anulo",
    errors: {
      invalid: "Plotëso emrin, mbiemrin dhe një email të vlefshëm.",
      exists: "Ky email është tashmë në ekip.",
      failed: "Ftesa nuk u dërgua. Provo sërish pas pak.",
    },
  },
  login: {
    title: "Hyr në SiteTrack",
    subtitle: "Fut email-in dhe të dërgojmë një link për të hyrë — pa fjalëkalim.",
    email: "Email",
    emailPlaceholder: "emri@shembull.com",
    send: "Dërgo linkun",
    sending: "Duke dërguar…",
    footer: "Llogaritë krijohen vetëm me ftesë.",
    invalidEmail: "Shkruaj një adresë email të vlefshme.",
    noAccount: "Ky email nuk ka llogari në SiteTrack.",
    deactivated: "Llogaria jote është çaktivizuar.",
    checkTitle: "Shiko email-in",
    checkSentTo: "Të dërguam një link te",
    steps: ["Hap email-in", "Shtyp butonin «Hyr në SiteTrack»", "Je brenda — pa fjalëkalim"],
    notArrived: "Nuk erdhi?",
    resend: "Dërgo sërish",
    wait: "Prit një minutë para se ta kërkosh sërish.",
    changeEmail: "Ndrysho email-in",
    expiredTitle: "Ky link ka skaduar",
    expiredBody:
      "Linqet e hyrjes vlejnë 24 orë dhe përdoren vetëm një herë. Kërko një të ri më poshtë.",
    sendNew: "Dërgo një link të ri",
  },
  roles: {
    owner: "Pronar",
    engineer: "Inxhinier",
    technician: "Teknik",
  },
  common: {
    logout: "Dil",
    currency: "L",
    placeholder: "Në ndërtim",
  },
} as const;
